# Generated by Django 3.2.14 on 2022-08-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('isMale', models.BooleanField()),
                ('phoneNumber', models.CharField(max_length=12)),
            ],
        ),
    ]
