# Generated by Django 4.0.6 on 2022-08-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='last_revenue_billion',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
