# Generated by Django 4.0.6 on 2022-08-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_generalclasses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('targeted_customers', models.CharField(max_length=255)),
                ('targeted_cost_range', models.CharField(max_length=255)),
                ('Limited', models.BooleanField(default=False)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
