# Generated by Django 4.0.6 on 2022-08-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
