# Generated by Django 4.0.6 on 2022-08-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_brandhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandhistory',
            name='modification_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='brandhistory',
            name='modified_by',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
