# Generated by Django 4.0.6 on 2022-08-05 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_categories_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandsClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
                ('targeted_customers', models.CharField(max_length=255)),
                ('quality', models.CharField(max_length=255)),
                ('exclusive', models.BooleanField(default=False)),
                ('remarks', models.TextField()),
                ('class_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.brand')),
                ('general_class', models.ForeignKey(default='Need to be added manually', on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.generalclasses')),
            ],
        ),
    ]
