# Generated by Django 4.0.6 on 2022-08-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_brandhistory_modification_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandhistory',
            old_name='last_revenue',
            new_name='last_revenue_billion',
        ),
    ]
