# Generated by Django 4.0.6 on 2022-08-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_rename_last_revenue_brandhistory_last_revenue_billion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandhistory',
            name='modification_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
