# Generated by Django 4.0.6 on 2022-08-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_brandsclasses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandsclasses',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
