# Generated by Django 4.0.6 on 2022-08-05 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_generalclasses_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ongoing_product', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.brand')),
                ('car_class', models.ForeignKey(default='Need to be added manually', on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.brandsclasses')),
                ('category', models.ForeignKey(default='Need to be added manually', on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.categories')),
            ],
        ),
    ]
