# Generated by Django 4.0.6 on 2022-08-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_brandhistory_modification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandhistory',
            name='modification_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='brandhistory',
            name='modified_by',
            field=models.CharField(max_length=255),
        ),
    ]
