# Generated by Django 4.0.6 on 2022-08-02 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movies_info_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies_info',
            name='director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.director_info'),
            preserve_default=False,
        ),
    ]
