# Generated by Django 4.0.6 on 2022-08-02 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movies_info_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('movie_date', models.DateField()),
                ('showtime', models.TimeField()),
                ('subtitle', models.CharField(max_length=200)),
                ('screen', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reservtion_code', models.CharField(max_length=10)),
                ('ticket_class', models.CharField(max_length=50)),
                ('seat', models.CharField(max_length=4)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie_schedule')),
            ],
        ),
        migrations.RemoveField(
            model_name='user_feedback',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movies_info',
            name='director',
        ),
        migrations.AlterField(
            model_name='movies_info',
            name='genres',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='movies_info',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='director_info',
        ),
        migrations.DeleteModel(
            name='user_feedback',
        ),
        migrations.AddField(
            model_name='movie_schedule',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies_info'),
        ),
    ]
