# Generated by Django 4.0.6 on 2022-08-04 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_schedule_user_ticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('comment', models.TextField()),
                ('comment_date', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies_info')),
            ],
        ),
    ]
