# Generated by Django 4.0.6 on 2022-08-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainees',
            name='te_phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='tr_phone',
            field=models.IntegerField(blank=True),
        ),
    ]
