# Generated by Django 4.0.6 on 2022-08-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_trainees_te_phone_alter_trainers_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainees',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
