# Generated by Django 4.0.6 on 2022-08-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_trainees_id_alter_trainers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
