# Generated by Django 4.0.6 on 2022-08-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_company_alter_requset_company_alter_task_company'),
        ('users', '0002_rename_cpmpany_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
