# Generated by Django 3.2.14 on 2022-08-03 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('isMale', models.BooleanField()),
                ('phoneNumber', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='gather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=128)),
                ('maxLimit', models.IntegerField()),
                ('currentPlayers', models.IntegerField()),
                ('justFemales', models.BooleanField()),
                ('matchDateTime', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=4, max_digits=6)),
                ('city', models.CharField(max_length=128)),
                ('location', models.TextField()),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatheringApp.userinfo')),
            ],
        ),
    ]
