# Generated by Django 3.2.14 on 2022-08-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheringApp', '0002_auto_20220803_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gather',
            name='location',
            field=models.URLField(),
        ),
    ]
