# Generated by Django 3.2.14 on 2022-08-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheringApp', '0003_alter_gather_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gather',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
