# Generated by Django 3.2.14 on 2022-08-04 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220803_1439'),
        ('gatheringApp', '0005_gather_leaderphonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatherPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gather', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gatheringApp.gather')),
                ('players', models.ManyToManyField(to='users.userInfo')),
            ],
        ),
    ]
