# Generated by Django 4.0.6 on 2022-08-04 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_product_remove_electronic_brand_alter_brand_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Electronic',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='category.brand'),
            preserve_default=False,
        ),
    ]
