# Generated by Django 4.0.6 on 2022-08-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_delete_electronic_remove_product_name_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=int, max_length=255),
            preserve_default=False,
        ),
    ]
