# Generated by Django 4.1 on 2022-08-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0002_alter_product_options_remove_product_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
