# Generated by Django 4.1 on 2022-08-04 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citys', '0002_place_name_alter_city_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='rating',
            new_name='comments',
        ),
    ]
