# Generated by Django 4.1 on 2022-08-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citys', '0003_rename_rating_place_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(default='non'),
            preserve_default=False,
        ),
    ]
