# Generated by Django 4.0.6 on 2022-08-03 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminstration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=512)),
                ('password', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('Birthdate', models.DateField()),
                ('password', models.CharField(max_length=128)),
                ('mobile_number', models.CharField(max_length=128)),
                ('Department', models.CharField(max_length=128)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.adminstration')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('service_duration', models.CharField(max_length=128)),
                ('beneficiary_group', models.CharField(max_length=128)),
                ('Fees', models.IntegerField()),
                ('service_steps', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.adminstration')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cpmpany')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.service')),
            ],
        ),
        migrations.CreateModel(
            name='Requset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cpmpany')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.service')),
            ],
        ),
    ]
