# Generated by Django 4.0.6 on 2022-08-03 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_company_alter_requset_company_alter_task_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.adminstration'),
            preserve_default=False,
        ),
    ]
