# Generated by Django 4.0.6 on 2022-08-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=512)),
                ('address', models.TextField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
