# Generated by Django 4.0.6 on 2022-08-03 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=218)),
                ('c_type', models.CharField(max_length=218)),
                ('c_duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('c_price', models.FloatField()),
                ('c_trainee', models.ManyToManyField(to='Users.trainees')),
                ('c_trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.trainers')),
            ],
        ),
    ]
