# Generated by Django 4.0.6 on 2022-08-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
