# Generated by Django 4.0.6 on 2022-08-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_remove_car_branch_car_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='branch',
        ),
        migrations.AddField(
            model_name='car',
            name='branch',
            field=models.ManyToManyField(to='Cars.branch'),
        ),
    ]
