# Generated by Django 4.0.6 on 2022-08-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0004_remove_car_branch_car_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(),
        ),
    ]
