# Generated by Django 4.0.6 on 2022-08-03 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0005_alter_car_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='branch',
        ),
        migrations.AddField(
            model_name='car',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cars.branch'),
            preserve_default=False,
        ),
    ]
