# Generated by Django 4.1 on 2022-08-05 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise_name", models.CharField(max_length=512)),
                ("exercise_desc", models.TextField()),
                ("exercise_reps", models.IntegerField()),
                ("exercise_sets", models.IntegerField()),
                ("exercise_vid", models.URLField()),
                ("exercise_intensity", models.CharField(max_length=512)),
                (
                    "coach_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
