# Generated by Django 4.0.6 on 2022-08-02 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='name',
            new_name='restaurant_name',
        ),
        migrations.RenameField(
            model_name='restaurants',
            old_name='type_food',
            new_name='type_of_food',
        ),
    ]
